# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
  App\Service\UserApiService:
    arguments:
      $apiUrl: "%env(API_URL)%"
  App\Service\CharacterApiService:
    arguments:
      $apiUrl: "%env(API_URL)%"
  App\Controller\LoginController:
    arguments:
      $apiUrl: "%env(API_URL)%"
  App\Controller\RegistrationController:
    arguments:
      $apiUrl: "%env(API_URL)%"
  App\Controller\UserController:
    arguments:
      $apiUrl: "%env(API_URL)%"
  App\Service\ItemApiService:
    arguments:
      $apiUrl: "%env(API_URL)%"
  App\Service\LanguageApiService:
    arguments:
      $apiUrl: "%env(API_URL)%"
  App\Service\RaceApiService:
    arguments:
      $apiUrl: "%env(API_URL)%"
  App\Service\SpellApiService:
    arguments:
      $apiUrl: "%env(API_URL)%"
  App\Service\ClassApiService:
    arguments:
      $apiUrl: "%env(API_URL)%"
  App\Service\CampainApiService:
    arguments:
      $apiUrl: "%env(API_URL)%"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
